name: cuidapet_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^4.3.1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  asuka: any
  dio: ^4.0.4
  flutter_screenutil: ^5.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
